matrix:
  include:
    - DOCKER_IMAGE: debian/jessie:x86_64
      STACK_REPO: debian
      UPLOAD_RELEASE: stretch
    - DOCKER_IMAGE: debian/stretch:x86_64
      STACK_REPO: debian
      UPLOAD_RELEASE: stretch

pipeline:
  build:
    image: registry.icinga.com/build-docker/${DOCKER_IMAGE}
    environment:
      ICINGA_BUILD_TYPE: snapshot
    commands:
      - icinga-build-package
    # artifact: build
    # cache: ccache

  test:
    image: registry.icinga.com/build-docker/${DOCKER_IMAGE}
    commands:
      - find build/
      - icinga-build-test
    # use artifacts

  #upload:
  #  image: registry.icinga.com/build-docker/upload
  # environment:
  #  UPLOAD_TARGET: stack/snapshot/$${STACK_REPO}
  #commands:
  #  - icinga-build-upload-aptly --target $$UPLOAD_TARGET --release $$UPLOAD_RELEASE
  # use artifacts
  #only:
    #- tags
  #  - master
